repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: taskfile-pre-commit
        name: Taskfile Pre-Commit
        entry: task pre-commit
        language: system
        pass_filenames: false
