repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: helm-lint
        name: Helm Lint
        entry: bash -c 'cd platform-core && helm lint .'
        language: system
