repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # - repo: local
  #   hooks:
  #     - id: devbox-pre-commit
  #       name: DevBox Pre-Commit
  #       entry: devbox run pre-commit-run
  #       language: system
  #       pass_filenames: false
