version: "3"

tasks:
  install-prerequisites:
    silent: true
    cmds:
      - |
        # Install kind
        if ! command -v kind &> /dev/null; then
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.24.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
        fi
      - |
        # Install kubectl
        if ! command -v kubectl &> /dev/null; then
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
        fi
      - |
        # Install helm
        if ! command -v helm &> /dev/null; then
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        fi
      - |
        # Install Docker
        if ! command -v docker &> /dev/null; then
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo usermod -aG docker $USER
          newgrp docker
        fi

  create-cluster:
    cmds:
      - kind delete cluster --name kind || true
      - kind get clusters | grep -q "kind" || kind create cluster --name kind # --config kind-config.yaml

  helm-dependency-update:
    cmds:
      - helm dependency update platform-core
      - for dir in $(find platform-core/charts/ -maxdepth 1 -mindepth 1 -type d); do helm dependency update $dir; done

  helm-lint:
    cmds:
      - helm lint platform-core

  create-namespaces:
    cmds:
      - kubectl apply -f namespaces

  helm-dry-run:
    cmds:
      - helm install --dry-run platform-core platform-core > .helm-dry-run

  helm-install:
    cmds:
      - helm upgrade --install platform-core platform-core

  increment-chart-version:
    cmds:
      - |
        #!/bin/bash
        CHART_FILE="platform-core/Chart.yaml"
        VERSION=$(grep '^version:' $CHART_FILE | awk '{print $2}')
        VERSION_PARTS=(${VERSION//./ })
        PATCH_VERSION=$((VERSION_PARTS[2] + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
        sed -i "s/^version: .*/version: $NEW_VERSION/" $CHART_FILE
        echo "Updated chart version to $NEW_VERSION"

  package-chart:
    cmds:
      - helm package platform-core

  ci:
    cmds:
      - task install-prerequisites
      - task helm-dependency-update
      - task helm-lint
      - task create-cluster
      - task helm-dry-run
      - task create-namespaces
      - task helm-install
      - task increment-chart-version
      - task package-chart
      - kubectl get pods --all-namespaces
