apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-wildcard-tls
  namespace: istio-system
spec:
  secretName: istio-wildcard-tls-cert
  issuerRef:
    name: letsencrypt-prd
    kind: ClusterIssuer
  dnsNames:
    - "*.cace-1-dev.dramisinfo.com"
