{{- if .Values.bootstrap.gatekeeper.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  destination:
    namespace: gatekeeper-system
    server: "https://kubernetes.default.svc"
  project: default
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - .spec.preserveUnknownFields
    - .spec.names.singular
  source:
    repoURL: "https://open-policy-agent.github.io/gatekeeper/charts"
    targetRevision: "3.17.1"
    chart: gatekeeper
    helm:
      valuesObject:
        replicas: 2
        auditInterval: 60
        constraintViolationsLimit: 20
        auditFromCache: false
        emitAdmissionEvents: false
        emitAuditEvents: false
        logLevel: INFO
        image:
          release: v3.17.1
        controllerManager:
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8888"
            prometheus.io/path: "/metrics"
        audit:
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8888"
            prometheus.io/path: "/metrics"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
{{- end -}}
