{{- if and .Values.bootstrap.gatekeeper.enabled .Values.bootstrap.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gatekeeper-audit
  namespace: gatekeeper-system
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
  labels:
    app: gatekeeper
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gatekeeper
      control-plane: audit-controller
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
{{- end -}}
