{{- if .Values.bootstrap.opslevel.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opslevel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: opslevel
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "oci://registry.replicated.com/opslevel/helm"
    targetRevision: "latest"
    chart: opslevel
    helm:
      valuesObject:
        opslevel:
          domain: "dramisinfo.com"
          subdomain: {{ printf "opslevel-%s" .Values.global.clusterName | quote }}
          ingress:
            create: true
            tls: true
            ingressClassName: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "vault-issuer"
              nginx.ingress.kubernetes.io/proxy-body-size: "4m"
              nginx.ingress.kubernetes.io/proxy-buffer-size: "4m"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
{{- end -}}
