{{- if .Values.bootstrap.cloudflared.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd-resource-finalizer
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  destination:
    namespace: cloudflared
    server: "https://kubernetes.default.svc"
  project: platform-networking
  source:
    repoURL: "https://community-charts.github.io/helm-charts"
    chart: cloudflared
    targetRevision: {{ .Values.bootstrap.cloudflared.targetRevision | quote }}
    helm:
      releaseName: cloudflared
      valuesObject: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipHooks=true
{{- end }}
