{{- if .Values.bootstrap.crossplane.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
      argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: crossplane-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://charts.crossplane.io/stable"
    targetRevision: "1.17.1"
    chart: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
{{- end -}}