{{- if .Values.bootstrap.argoEvents.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  destination:
    namespace: argo-events
    server: "https://kubernetes.default.svc"
  project: platform-foundations
  source:
    repoURL: "https://argoproj.github.io/argo-helm"
    targetRevision: "2.4.10"
    chart: argo-events
    helm:
      valuesObject:
        # Security context to comply with Gatekeeper psp-pods-must-run-as-nonroot policy
        controller:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
        webhook:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containerSecurityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
    {{- include "platform-core.defaultRetry" . | nindent 4 }}
{{- end -}}
