{{- if and .Values.bootstrap.gatekeeper.enabled .Values.bootstrap.gatekeeper.policies.enabled -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: psp-pods-must-run-as-nonroot
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "*"
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - cert-manager
      - istio-system
      - ingress-nginx
  parameters:
    runAsUser:
      rule: MustRunAsNonRoot
    exemptImages:
      - "gcr.io/k8s-minikube/*"
{{- end -}}
