{{- if .Values.bootstrap.monitoring.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hosts:
    - grafana.{{ .Values.global.clusterName }}.dramisinfo.com
  gateways:
    - istio-system/shared-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: prometheus-grafana
            port:
              number: 80
{{- end -}}
