{{- if .Values.bootstrap.monitoring.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
{{- end -}}
