{{- if .Values.bootstrap.istio.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  destination:
    namespace: istio-system
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      targetRevision: "1.28.4"
      chart: base
      helm:
        valuesObject:
          defaultRevision: default
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      targetRevision: "1.28.4"
      chart: istiod
      helm:
        valuesObject:
          profile: ambient
          global:
            istioNamespace: istio-system
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      targetRevision: "1.28.4"
      chart: cni
      helm:
        valuesObject:
          profile: ambient
          global:
            platform: {{ .Values.bootstrap.istio.platform | default "k3s" | quote }}
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      targetRevision: "1.28.4"
      chart: ztunnel
      helm:
        valuesObject: {}
    - repoURL: "https://istio-release.storage.googleapis.com/charts"
      targetRevision: "1.28.4"
      chart: gateway
      helm:
        valuesObject:
          name: istio-ingressgateway
          annotations:
            argocd.argoproj.io/sync-wave: "5"
          labels:
            istio: ingressgateway
          replicaCount: 2
          service:
            type: LoadBalancer
            ports:
              - name: http2
                port: 80
                targetPort: 8080
                protocol: TCP
              - name: https
                port: 443
                targetPort: 8443
                protocol: TCP
    - repoURL: "https://dysnix.github.io/charts"
      targetRevision: "0.3.2"
      chart: raw
      helm:
        valuesObject:
          resources:
            - apiVersion: networking.istio.io/v1
              kind: Gateway
              metadata:
                name: shared-gateway
                namespace: istio-system
                annotations:
                  argocd.argoproj.io/sync-wave: "5"
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
              spec:
                selector:
                  istio: ingressgateway
                servers:
                  - port:
                      number: 80
                      name: http
                      protocol: HTTP
                    hosts:
                      - "*.{{ .Values.global.clusterName }}.dramisinfo.com"
                    tls:
                      httpsRedirect: true
                  - port:
                      number: 443
                      name: https
                      protocol: HTTPS
                    hosts:
                      - "*.{{ .Values.global.clusterName }}.dramisinfo.com"
                    tls:
                      mode: SIMPLE
                      credentialName: istio-wildcard-tls-cert
            - apiVersion: cert-manager.io/v1
              kind: Certificate
              metadata:
                name: istio-wildcard-tls
                namespace: istio-system
                annotations:
                  argocd.argoproj.io/sync-wave: "5"
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
              spec:
                secretName: istio-wildcard-tls-cert
                issuerRef:
                  name: letsencrypt-prd
                  kind: ClusterIssuer
                dnsNames:
                  - "*.{{ .Values.global.clusterName }}.dramisinfo.com"
            - apiVersion: networking.istio.io/v1
              kind: VirtualService
              metadata:
                name: argocd-server
                namespace: argocd
                annotations:
                  argocd.argoproj.io/sync-wave: "5"
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
              spec:
                hosts:
                  - argo.{{ .Values.global.clusterName }}.dramisinfo.com
                gateways:
                  - istio-system/shared-gateway
                http:
                  - match:
                      - uri:
                          prefix: /
                    route:
                      - destination:
                          host: argocd-server
                          port:
                            number: 80
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jsonPointers:
        - /webhooks/0/failurePolicy
        - /webhooks/0/clientConfig/caBundle
    - group: apps
      kind: DaemonSet
      name: ztunnel
      jsonPointers:
        - /metadata/annotations/deprecated.daemonset.template.generation
      jqPathExpressions:
        - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
    - group: apps
      kind: DaemonSet
      name: istio-cni-node
      jsonPointers:
        - /metadata/annotations/deprecated.daemonset.template.generation
{{- end -}}
