{{- if .Values.bootstrap.istio.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-shared-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://github.com/istio/istio.git"
    targetRevision: "1.28.1"
    path: "manifests/charts/gateways/istio-ingress"
    helm:
      valuesObject:
        gateways:
          istio-ingressgateway:
            name: shared-gateway
            labels:
              istio: ingressgateway
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end -}}
