apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-operator
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: cloudflare-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflare-operator
    spec:
      serviceAccountName: cloudflare-operator
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --leader-elect
          envFrom:
            - configMapRef:
                name: cloudflare-operator-config
            - secretRef:
                name: {{ .Values.externalSecret.targetSecretName }}
          env:
            - name: WATCH_NAMESPACE
              value: ""
          resources:
{{ toYaml .Values.resources | indent 12 }}
