apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-operator
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/component: operator
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.imagePullSecrets }}
{{- end }}
