{{- if and .Values.bootstrap.gatekeeper.enabled .Values.bootstrap.gatekeeper.policies.enabled -}}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: psp-pods-must-run-as-nonroot
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  enforcementAction: {{ .Values.bootstrap.gatekeeper.policies.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "*"
    excludedNamespaces:
      {{- if .Values.bootstrap.gatekeeper.policies.excludedNamespaces }}
      {{- toYaml .Values.bootstrap.gatekeeper.policies.excludedNamespaces | nindent 6 }}
      {{- else }}
      - kube-system
      - gatekeeper-system
      - cert-manager
      - istio-system
      - ingress-nginx
      - argocd
      {{- end }}
  parameters:
    runAsUser:
      rule: MustRunAsNonRoot
    {{- if .Values.bootstrap.gatekeeper.policies.exemptImages }}
    exemptImages:
      {{- toYaml .Values.bootstrap.gatekeeper.policies.exemptImages | nindent 6 }}
    {{- end }}
{{- end -}}
