{{- if and .Values.bootstrap.gatekeeper.enabled .Values.bootstrap.prometheus.enabled .Values.bootstrap.grafana.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opa-scorecard-reader
rules:
  - apiGroups:
      - "constraints.gatekeeper.sh"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
{{- end -}}
