{{- if and .Values.bootstrap.gatekeeper.enabled .Values.bootstrap.prometheus.enabled .Values.bootstrap.grafana.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opa-scorecard-exporter
  namespace: opa-scorecard
{{- end -}}
