{{- if .Values.bootstrap.nats.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nats
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://nats-io.github.io/k8s/helm/charts/"
    targetRevision: "1.2.6"
    chart: nats
    helm:
      valuesObject:
        config:
          cluster:
            enabled: true
            replicas: 3
          jetstream:
            enabled: true
            fileStore:
              pvc:
                size: 10Gi
        container:
          env:
            GOMEMLIMIT: 2GiB
          merge:
            resources:
              requests:
                cpu: "500m"
                memory: 2Gi
              limits:
                cpu: "500m"
                memory: 2Gi
        podTemplate:
          topologySpreadConstraints:
            kubernetes.io/hostname:
              maxSkew: 1
              whenUnsatisfiable: DoNotSchedule
        service:
          merge:
            spec:
              type: ClusterIP
        natsBox:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
{{- end -}}
