{{- if .Values.bootstrap.nats.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nats
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://nats-io.github.io/k8s/helm/charts/"
    targetRevision: "1.3.6"
    chart: nats
    helm:
      valuesObject:
        config:
          cluster:
            enabled: true
            replicas: 3
          jetstream:
            enabled: true
            fileStore:
              pvc:
                size: 10Gi
          {{- if .Values.bootstrap.nats.gateway.enabled }}
          gateway:
            enabled: true
            {{- if .Values.bootstrap.nats.gateway.port }}
            port: {{ .Values.bootstrap.nats.gateway.port }}
            {{- end }}
            merge:
              {{- if .Values.bootstrap.nats.gateway.name }}
              name: {{ .Values.bootstrap.nats.gateway.name | quote }}
              {{- else }}
              name: {{ .Values.global.clusterName | quote }}
              {{- end }}
              {{- if .Values.bootstrap.nats.gateway.advertise }}
              advertise: {{ .Values.bootstrap.nats.gateway.advertise | quote }}
              {{- end }}
              {{- if .Values.bootstrap.nats.gateway.gateways }}
              gateways:
                {{- range .Values.bootstrap.nats.gateway.gateways }}
                - name: {{ .name | quote }}
                  url: {{ .url | quote }}
                {{- end }}
              {{- end }}
          {{- end }}
        {{- if .Values.bootstrap.nats.gateway.enabled }}
        service:
          merge:
            spec:
              type: LoadBalancer
          ports:
            gateway:
              enabled: true
        {{- end }}
        natsBox:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
{{- end -}}
