{{- if .Values.bootstrap.cnpg.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  destination:
    namespace: cnpg-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: "https://cloudnative-pg.github.io/charts"
    targetRevision: "0.27.0"
    chart: cloudnative-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipHooks=true
      - Timeout=600
      - Validate=false
      - Wait=true
      - PruneEmpty=true
{{- end -}}
