{{- if .Values.bootstrap.crossplane.dynamicDns.enabled -}}
apiVersion: platform.dramisinfo.com/v1alpha1
kind: XDynamicDnsRecord
metadata:
  name: vpn-dramisinfo
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  subscriptionId: {{ .Values.bootstrap.crossplane.dynamicDns.subscriptionId | quote }}
  recordName: {{ .Values.bootstrap.crossplane.dynamicDns.recordName | quote }}
  zoneName: {{ .Values.bootstrap.crossplane.dynamicDns.zoneName | quote }}
  resourceGroupName: {{ .Values.bootstrap.crossplane.dynamicDns.resourceGroupName | quote }}
  ttl: {{ .Values.bootstrap.crossplane.dynamicDns.ttl }}
{{- end }}
