apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-201"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
data:
  baseDomain: "{{ .Values.global.clusterName }}.dramisinfo.com"
  clusterName: "{{ .Values.global.clusterName }}"
  azureLocation: "{{ .Values.global.azure.location }}"
  azureTenantId: "{{ .Values.global.azure.tenantId }}"
  azureSubscriptionId: "{{ .Values.global.azure.subscriptionId }}"
