name: Build, Test, and Publish Helm Chart

on:
  pull_request:
    branches:
      - main

jobs:
  test-packate-publish:
    runs-on: self-hosted
    name: Build, Test, and Publish Helm Chart
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Install helm-unittest plugin
        run: |
          helm plugin list | grep "unittest"
          if ! helm plugin list | grep -q "unittest"; then
              helm plugin install https://github.com/quintush/helm-unittest
          else
              echo "Helm unittest plugin is already installed."
          fi

      - name: Lint Helm chart
        run: helm lint ./platform-core

      - name: Run Helm tests
        run: helm unittest ./platform-core
