name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Helm Lint
    # Skip if commit message contains [skip ci] or [ci skip]
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Lint Helm chart
        run: helm lint platform-core

      - name: Test Helm template generation
        run: helm template platform-core platform-core

  test-combinations:
    runs-on: ubuntu-latest
    name: Test Chart Combinations
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        test-scenario:
          - name: "minimal"
            values: |
              global:
                clusterName: "test"
              bootstrap:
                nats:
                  enabled: true
          - name: "monitoring-stack"
            values: |
              global:
                clusterName: "test"
              bootstrap:
                prometheus:
                  enabled: true
                grafana:
                  enabled: true
                loki:
                  enabled: true
                nats:
                  enabled: true
          - name: "security-stack"
            values: |
              global:
                clusterName: "test"
              bootstrap:
                clusterIssuer:
                  letsencrypt:
                    enabled: true
                externalSecretOperator:
                  enabled: true
                nats:
                  enabled: true
          - name: "infrastructure-stack"
            values: |
              global:
                clusterName: "test"
              bootstrap:
                crossplane:
                  enabled: true
                terraformOperator:
                  enabled: true
                atlas:
                  enabled: true
                nats:
                  enabled: true
          - name: "nats-gateway"
            values: |
              global:
                clusterName: "test"
              bootstrap:
                nats:
                  enabled: true
                  gateway:
                    enabled: true
                    name: "test-cluster"
                    port: 7222
          - name: "full-stack"
            values: |
              global:
                clusterName: "test"
              bootstrap:
                clusterIssuer:
                  letsencrypt:
                    enabled: true
                crossplane:
                  enabled: true
                atlas:
                  enabled: true
                terraformOperator:
                  enabled: true
                externalSecretOperator:
                  enabled: true
                prometheus:
                  enabled: true
                grafana:
                  enabled: true
                loki:
                  enabled: true
                nats:
                  enabled: true
                  gateway:
                    enabled: true
                    name: "test-cluster"
                    port: 7222
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Create values file
        run: |
          cat > test-values.yaml << 'EOF'
          ${{ matrix.test-scenario.values }}
          EOF

      - name: Test Helm template with ${{ matrix.test-scenario.name }} configuration
        run: |
          echo "Testing ${{ matrix.test-scenario.name }} configuration..."
          helm template platform-core platform-core -f test-values.yaml

      - name: Test Helm lint with ${{ matrix.test-scenario.name }} configuration
        run: |
          helm lint platform-core -f test-values.yaml
  release:
    runs-on: ubuntu-latest
    name: Automatic Version Bump and Release
    needs: [lint, test-combinations]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    outputs:
      version: ${{ steps.bump_version.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine version bump type
        id: bump_type
        run: |
          # Get the latest commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          
          # Determine bump type based on conventional commits
          if echo "$COMMIT_MSG" | grep -qE "^(feat|feature)(\(.+\))?!:|^BREAKING CHANGE:|breaking change"; then
            echo "bump_type=major" >> $GITHUB_OUTPUT
            echo "Detected MAJOR version bump (breaking change)"
          elif echo "$COMMIT_MSG" | grep -qE "^feat(\(.+\))?:|^feature(\(.+\))?:"; then
            echo "bump_type=minor" >> $GITHUB_OUTPUT
            echo "Detected MINOR version bump (new feature)"
          else
            echo "bump_type=patch" >> $GITHUB_OUTPUT
            echo "Detected PATCH version bump (bug fix/other)"
          fi

      - name: Bump version in Chart.yaml
        id: bump_version
        env:
          BUMP_TYPE: ${{ steps.bump_type.outputs.bump_type }}
        run: |
          CHART_FILE="platform-core/Chart.yaml"
          CURRENT_VERSION=$(grep '^version:' $CHART_FILE | awk '{print $2}')
          echo "Current version: $CURRENT_VERSION"
          
          # Parse version components
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          # Increment version based on bump type
          case $BUMP_TYPE in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac
          
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION"
          
          # Update Chart.yaml
          sed -i "s/^version: .*/version: $NEW_VERSION/" $CHART_FILE
          
          # Output for next steps
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version bump
        env:
          NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add platform-core/Chart.yaml
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git push origin main

      - name: Create and push git tag
        env:
          NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
        run: |
          git tag -a "v$NEW_VERSION" -m "Release version $NEW_VERSION"
          git push origin "v$NEW_VERSION"

  update-platform-tools:
    runs-on: ubuntu-latest
    name: Update platform-tools
    needs: release
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout platform-tools repository
        uses: actions/checkout@v4
        with:
          repository: DramisInfo/platform-tools
          path: platform-tools
          token: ${{ secrets.GH_TOKEN }}

      - name: Update platform-core.yaml with new version
        env:
          NEW_VERSION: ${{ needs.release.outputs.version }}
        run: |
          sed -i "s/targetRevision: \".*\"/targetRevision: \"v$NEW_VERSION\"/" platform-tools/overlays/cace-1-dev/patches/platform-core.yaml
          sed -i "s/targetRevision: \".*\"/targetRevision: \"v$NEW_VERSION\"/" platform-tools/overlays/cace-2-dev/patches/platform-core.yaml

      - name: Commit and push changes
        env:
          NEW_VERSION: ${{ needs.release.outputs.version }}
        run: |
          cd platform-tools
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add overlays/dev/patches/platform-core.yaml
          git commit -m "Update platform-core to version v$NEW_VERSION"
          git push origin main
