name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    name: Build and Test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Task
        run: |
          sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Run CI tasks
        run: task ci

  release:
    runs-on: self-hosted
    name: Release
    needs: test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Retrieve version
        id: get_version
        run: echo "VERSION=$(cat .version)" >> $GITHUB_ENV

      - name: Print version
        run: echo "The released version is ${{ env.VERSION }}"

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Package Helm chart
        run: helm package ./platform-core --version ${{ env.VERSION }} --app-version ${{ env.VERSION }}

      - name: Publish Helm chart
        env:
          HELM_REPO_URL: ${{ secrets.HELM_REPO_URL }}
          HELM_REPO_USERNAME: ${{ secrets.HELM_REPO_USERNAME }}
          HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
        run: |
          export HELM_EXPERIMENTAL_OCI=1
          echo $HELM_REPO_PASSWORD | helm registry login harbor.platform.dramisinfo.com --username $HELM_REPO_USERNAME --password-stdin
          helm push ./platform-core-*.tgz $HELM_REPO_URL

  update-platform-tools:
    runs-on: self-hosted
    name: Update platform-tools
    needs: release
    steps:
      - name: Checkout platform-tools repository
        uses: actions/checkout@v3
        with:
          repository: DramisInfo/platform-tools
          path: platform-tools
          token: ${{ secrets.GH_TOKEN }}

      - name: Update platform-core.yaml with new version
        run: |
          NEW_VERSION=$(cat .version)
          sed -i "s/targetRevision: \".*\"/targetRevision: \"$NEW_VERSION\"/" platform-tools/overlays/dev/patches/platform-core.yaml

      - name: Commit and push changes
        run: |
          cd platform-tools
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add overlays/dev/patches/platform-core.yaml
          git commit -m "Update platform-core to version $NEW_VERSION"
          git push origin main
