name: Build, Test, and Publish Helm Chart

on:
  pull_request:
    branches:
      - main

jobs:
  test-packate-publish:
    runs-on: self-hosted
    name: Build, Test, and Publish Helm Chart
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Install helm-unittest plugin
        run: |
          helm plugin list | grep "unittest"
          if ! helm plugin list | grep -q "unittest"; then
              helm plugin install https://github.com/quintush/helm-unittest
          else
              echo "Helm unittest plugin is already installed."
          fi

      - name: Lint Helm chart
        run: helm lint ./platform-core

      - name: Run Helm tests
        run: helm unittest ./platform-core

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: semantic-release

      - name: Package Helm chart
        run: helm package ./platform-core

      - name: Publish Helm chart
        env:
          HELM_REPO_URL: ${{ secrets.HELM_REPO_URL }}
          HELM_REPO_USERNAME: ${{ secrets.HELM_REPO_USERNAME }}
          HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
        run: |
          export HELM_EXPERIMENTAL_OCI=1
          echo $HELM_REPO_PASSWORD | helm registry login harbor.platform.dramisinfo.com --username $HELM_REPO_USERNAME --password-stdin
          helm push ./platform-core-*.tgz $HELM_REPO_URL
