name: Build, Test, and Publish Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-publish:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/quintush/helm-unittest || true

      - name: Lint Helm chart
        run: helm lint ./platform-core

      - name: Run Helm tests
        run: helm unittest ./platform-core

      - name: Package Helm chart
        run: helm package ./platform-core

      - name: Publish Helm chart
        env:
          HELM_REPO_URL: https://registry.platform.dramisinfo.com/platform/
          HELM_REPO_USERNAME: ${{ secrets.HELM_REPO_USERNAME }}
          HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
        run: |
          helm repo add platform $HELM_REPO_URL --username $HELM_REPO_USERNAME --password $HELM_REPO_PASSWORD --insecure-skip-tls-verify
          helm push ./platform-core-*.tgz platform --insecure-skip-tls-verify
