name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Package Helm chart
        run: helm package ./platform-core

      - name: Publish Helm chart
        env:
          HELM_REPO_URL: ${{ secrets.HELM_REPO_URL }}
          HELM_REPO_USERNAME: ${{ secrets.HELM_REPO_USERNAME }}
          HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
        run: |
          export HELM_EXPERIMENTAL_OCI=1
          echo $HELM_REPO_PASSWORD | helm registry login harbor.platform.dramisinfo.com --username $HELM_REPO_USERNAME --password-stdin
          helm push ./platform-core-*.tgz $HELM_REPO_URL
